changelog:
  categories:
    - title: dump-oidc-token
      labels:
        - "action:dump-oidc-token"
    - title: signed-commit
      labels:
        - "action:signed-commit"
    - title: create-pull-request
      labels:
        - "action:create-pull-request"
    - title: Features
      labels:
        - feature
    - title: Bug Fixes
      labels:
        - bugfix
    - title: Dependencies
      labels:
        - dependencies
