changelog:
  categories:
    - title: dump-oidc-token
      labels:
        - "action:dump-oidc-token"
    - title: Features
      labels:
        - feature
    - title: Bug Fixes
      labels:
        - bugfix
    - title: Dependencies
      labels:
        - dependencies
